version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - ACCOUNT_NAME=
      - WEBHOOK_ID=
      - WEBHOOK_SECRET=
    ports:
      - "80:3000"
    command: "npm start"